[package]
name = "komron_8"
version = "0.1.0"
authors = ["komron <komron_aripov@cdl.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2"
digits_iterator = "0.1"
